In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import re
from sklearn.utils import shuffle




In [19]:
#READING THE CSV FILE
tw1=pd.read_csv('predicted_sentiment.csv',delimiter=',')
#SHUFFLING THE DATA
tw1 = tw1.sample(frac=1).reset_index(drop=True)
twitter=tw1.copy()
twitter

Unnamed: 0              user_id            status_id  created_at  \
0           11754            495666073  1122749472180596736  1556519308   
1            1307           1956754434  1122886338930511873  1556551940   
2           13908             56569304  1122678243365203972  1556502326   
3            1818            115126046  1122921162143494144  1556560242   
4            5779   793949726483693569  1122729591590637573  1556514568   
5           13576             17823286  1122687880596475904  1556504623   
6            1172   733388252355297281  1122925194442461186  1556561203   
7           10828           3170242412  1122813040896790530  1556534464   
8            1625   856181385060536320  1122922617176973312  1556560589   
9            4715            532462766  1122896858551148551  1556554448   
10           4265           1006501890  1122900606761484288  1556555341   
11           3621  1009528938060832771  1122693499789377536  1556505963   
12            460  1096128833693061121  1122800641632624640  1556531508   
13            479           1606472113  1122679651648720896  1556502661   
14           3083            614558902  1122793661178114048  1556529843   
15           9123   804362104048230400  1122847148553330688  1556542596   
16           1631            937588736  1122922537845972994  1556560570   
17          11608           1645876892  1122758594603233280  1556521483   
18           1930             74085754  1122920293083664385  1556560035   
19           7889             14119118  1122863064657924096  1556546391   
20            662            230082885  1122927469932101632  1556561746   
21           6896  1087115363735740417  1122874884663730176  1556549209   
22           7385            374658826  1122868846078111744  1556547769   
23          13303             16472258  1122694084492009472  1556506103   
24          11681            221264989  1122754847865036800  1556520590   
25           6580   745272072998391809  1122878433694973953  1556550055   
26           1149           1179710990  1122803456895533056  1556532179   
27          12868            101043870  1122704988352831489  1556508702   
28           1008             15945641  1122880875283329024  1556550637   
29           9504           2434465868  1122842560068771840  1556541502   
...           ...                  ...                  ...         ...   
14027        7837            304691182  1122863528833093638  1556546501   
14028        5954            469737625  1122772618476605440  1556524827   
14029        1425  1021210507783487488  1122923767175491584  1556560863   
14030        9019  1061697883336921088  1122848415841341440  1556542898   
14031        8829             15880488  1122851184828669952  1556543558   
14032        6956            207682058  1122874326737408001  1556549076   
14033        4752           3383591561  1122896449828790272  1556554350   
14034        8984             97036677  1122848903878123522  1556543014   
14035        3649           2787307992  1122906151769608192  1556556663   
14036        3291            217548189  1122886198689718282  1556551906   
14037        5440   714530190945345537  1122889885126406144  1556552785   
14038        3205             36676776  1122909641250181126  1556557495   
14039        3324   834419982712729600  1122875587507499008  1556549376   
14040        5421             21990739  1122890023706091521  1556552818   
14041        2466            783185311  1122915917510402048  1556558992   
14042        1218  1091758815442231296  1122876887540228097  1556549686   
14043        8149             59219530  1122859593045106689  1556545563   
14044        4150  1032030545868451840  1122901591777054721  1556555576   
14045        2664             56040110  1122914082280095745  1556558554   
14046        8014             63770391  1122840347971870720  1556540974   
14047       12083            336847301  1122732480824528896  1556515257   
14048        8060             40

In [20]:
#READING THE CSV FILE
dg=pd.read_csv('train.tsv',delimiter='	')
#SHUFFLING THE DATA
dg = dg.sample(frac=1).reset_index(drop=True)
df=dg.copy()

df.columns=["ID","label","statement","subject","speaker","speakers_job_title","state_info","job_affiliation","barely_true","false","half_true","mostly_true","pants_on_fire","context"]
df

ID        label  \
0       9106.json  barely-true   
1        169.json        false   
2       5520.json         true   
3       9363.json  mostly-true   
4       8182.json    half-true   
5       2763.json    half-true   
6       4041.json         true   
7      11662.json    half-true   
8       8983.json  mostly-true   
9       6131.json    half-true   
10     11998.json    half-true   
11     10665.json  mostly-true   
12        57.json         true   
13      1445.json  mostly-true   
14      8808.json  mostly-true   
15       417.json        false   
16      8903.json        false   
17      9067.json    half-true   
18      1642.json    half-true   
19     11918.json  barely-true   
20      2042.json        false   
21      4456.json    half-true   
22      6258.json  barely-true   
23      3969.json         true   
24      1570.json  barely-true   
25      2824.json         true   
26     12539.json  mostly-true   
27      8530.json  mostly-true   
28     12184.json  mostly-true   
29      4385.json   pants-fire   
...           ...          ...   
10209   8740.json    half-true   
10210   6633.json         true   
10211   3914.json    half-true   
10212   9704.json  mostly-true   
10213   7805.json    half-true   
10214   4253.json  barely-true   
10215   2856.json    half-true   
10216   7254.json        false   
10217   9917.json    half-true   
10218   5331.json        false   
10219   6644.json  mostly-true   
10220   5433.json  barely-true   
10221  11483.json        false   
10222   2198.json         true   
10223   1490.json         true   
10224   5811.json  barely-true   
10225   7266.json         true   
10226  11384.json        false   
10227   8072.json        false   
10228   2384.json    half-true   
10229  11291.json  mostly-true   
10230   6677.json  mostly-true   
10231   2307.json         true   
10232   7774.json  mostly-true   
10233   1441.json   pants-fire   
10234   5474.json    half-true   
10235  11892.json  mostly-true   
10236   9639.json  barely-true   
10237   5609.json   pants-fire   
10238   7015.json        false   

                                               statement  \
0      We have been teaching these (Common Core) stan...   
1      Obama "refused to not only put his hand on his...   
2      In the last two years, super PACs raised more ...   
3      Milwaukee has seen an uptick in violence since...   
4      Floridas high school graduation rates continue...   
5      Says Washington state has consistently ranked ...   
6      Creeping defense commitments in (the Middle Ea...   
7      In Texas, weve had three ISIS-related incident...   
8      Gun marketplaces on Facebook mean ANYONE can b...   
9      As Virginia lost over 65,000 jobs, (Tim) Kaine...   
10     For every time the state gets paid a dollar in...   
11     Rhode Island has the second highest per enroll...   
12     Thirty-four percent of Hispanics don't have an...   
13     I have had the challenge during this administr...   
14     Marijuana today is genetically modified, with ...   
15     Obama "has no experience or background at all ...   
16                            On adoption by gay couples   
17     Says President Barack Obama was responsible fo...   
18     An attack on a healthy 22-year-old homosexual ...   
19     Says the one person (Donald Trump)has suggeste...   
20     On whether BPs $20 billion fund to compensate ...   
21     Under President Barack Obamas jobs bill, state...   
22     Bill OBriens Tea Party legislature tried to re...   
23     The right-to-work states are creating a lot mo...   
24     Obama has proposed a 1.4% pay increase for act...   
25     Nobody has played clips over and over ...of Pr...   
26     @realDonaldTrump is coming to San Antonio, whi...   
27     Says Chris Christie vetoed Planned Parenthood ...   
28     I have 2 and a half million more votes than he...   
29     Says Florida U.S. Reps. Corrine Brown, Alcee H...   
...                                           

In [21]:

unique=set(df["label"])
print(unique)
del df["ID"]



{'pants-fire', 'true', 'mostly-true', 'barely-true', 'false', 'half-true'}


In [22]:
df.speakers_job_title.replace(np.NaN, 'unknown', inplace=True)
df.state_info.replace(np.NaN, 'unknown', inplace=True)
df.dropna(inplace=True)
df.isnull().sum()

label                 0
statement             0
subject               0
speaker               0
speakers_job_title    0
state_info            0
job_affiliation       0
barely_true           0
false                 0
half_true             0
mostly_true           0
pants_on_fire         0
context               0
dtype: int64

In [23]:
def replace (s):
    if s=="mostly-true":
        return 0
    elif s=="barely-true":
        return 1
    elif s=="half-true":
        return 2
    elif s=="true":
        return 3
    elif s=="false":
        return 4
    elif s=="pants-fire":
        return 5
   
    
df["output"]=df.label.apply(replace)
output=df["output"]
unique=set(df["output"])
print(unique)

{0, 1, 2, 3, 4, 5}


CREATING A TOKENIZED FORM OF DATA TO WORK UPON

In [24]:
d=df["statement"]
statement=d.values
statement.shape
subject=df["subject"].values




In [25]:
word_data=[]

for i in range(len(statement)):
    word_data.append(statement[i])
print(len(word_data))

10137


STATEMENT TOKENIZATION

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

# create the transform
vectorizer = TfidfVectorizer()
# tokenize and build vocab
vectorizer.fit(word_data)
# summarize
vocab = vectorizer.vocabulary_
print(vectorizer.idf_)
# encode document
vector = vectorizer.transform(word_data)
# summarize encoded vector
print(vector.shape)
x=vector.toarray()

print(vocab)





[9.12543373 3.76257784 9.53089884 ... 9.53089884 9.53089884 9.53089884]
(10137, 12136)
{'we': 11798, 'have': 5259, 'been': 1516, 'teaching': 10835, 'these': 10973, 'common': 2543, 'core': 2827, 'standards': 10371, 'in': 5659, 'florida': 4578, 'schools': 9698, 'since': 10037, '2010': 214, 'obama': 7584, 'refused': 9075, 'to': 11063, 'not': 7539, 'only': 7702, 'put': 8780, 'his': 5388, 'hand': 5184, 'on': 7694, 'heart': 5293, 'during': 3772, 'the': 10942, 'pledge': 8296, 'of': 7638, 'allegiance': 927, 'but': 1965, 'say': 9632, 'last': 6387, 'two': 11324, 'years': 12078, 'super': 10639, 'pacs': 7916, 'raised': 8871, 'more': 7240, 'than': 10927, '180': 115, 'million': 7103, 'with': 11967, 'roughly': 9496, 'half': 5166, 'it': 6023, 'coming': 2520, 'from': 4740, 'fewer': 4444, '200': 201, 'rich': 9376, 'people': 8118, 'and': 1016, '20': 200, 'percent': 8123, 'corporations': 2838, 'milwaukee': 7108, 'has': 5241, 'seen': 9785, 'an': 1008, 'uptick': 11506, 'violence': 11649, 'period': 8137, 'ca

SUBJECT TOKENIZATION

In [27]:
tweet=twitter["text"]

In [28]:
tweets=[]

for i in range(len(tweet)):
    tweets.append(tweet[i])
print(len(tweets))

14057


In [29]:
vectorizer = TfidfVectorizer(vocabulary=vocab)
vectorizer.fit(tweets)
vector5 = vectorizer.transform(tweets)
# summarize encoded vector
print(vector5.shape)
x5=vector5.toarray()




(14057, 12136)


In [31]:
y=df["label"].values

In [32]:
from sklearn import model_selection
x_train, x_test, y_train, y_test = model_selection.train_test_split(x, y, test_size = 0.25,random_state=0)

In [33]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(x,y)
#y_pred = clf.predict(x_test)

#train_score = clf.score(x_train, y_train)
#test_score = clf.score(x_test, y_test)

#print(test_score)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [34]:
output=clf.predict(x5)
prob=clf.predict_proba(x5)
print(prob)
output

[[0.19569076 0.21416514 0.3215316  0.12446794 0.02786004 0.11628452]
 [0.19058538 0.17086813 0.21983866 0.2744101  0.04338013 0.10091759]
 [0.10818621 0.3197869  0.23428543 0.21080372 0.02478235 0.1021554 ]
 ...
 [0.14979941 0.19282102 0.26294008 0.15425896 0.04746052 0.19272001]
 [0.18885805 0.17267695 0.17724645 0.28223162 0.03575043 0.14323651]
 [0.18528527 0.2405401  0.16660335 0.15999202 0.06062134 0.18695792]]


array(['half-true', 'mostly-true', 'false', ..., 'half-true',
       'mostly-true', 'false'], dtype='<U11')

In [35]:
prob=np.array(prob)
probability=np.amax(prob,axis=1)
print(probability)
probability.shape

[0.3215316  0.2744101  0.3197869  ... 0.26294008 0.28223162 0.2405401 ]


(14057,)

In [36]:
print(output)
output.shape
Label=output.reshape((14057,1))
len(Label)

['half-true' 'mostly-true' 'false' ... 'half-true' 'mostly-true' 'false']


14057

In [37]:
ans=[]
for i in range (0,len(Label)):
    ans.append(Label[i][0])
print(ans)

['half-true', 'mostly-true', 'false', 'half-true', 'barely-true', 'false', 'half-true', 'half-true', 'barely-true', 'half-true', 'half-true', 'false', 'false', 'true', 'mostly-true', 'half-true', 'half-true', 'half-true', 'half-true', 'half-true', 'false', 'false', 'barely-true', 'half-true', 'half-true', 'true', 'barely-true', 'half-true', 'mostly-true', 'half-true', 'false', 'mostly-true', 'half-true', 'half-true', 'false', 'mostly-true', 'false', 'half-true', 'false', 'half-true', 'half-true', 'mostly-true', 'half-true', 'half-true', 'false', 'false', 'half-true', 'mostly-true', 'half-true', 'false', 'half-true', 'half-true', 'false', 'true', 'false', 'false', 'true', 'half-true', 'half-true', 'half-true', 'half-true', 'false', 'mostly-true', 'true', 'barely-true', 'false', 'mostly-true', 'half-true', 'half-true', 'false', 'mostly-true', 'half-true', 'false', 'half-true', 'false', 'half-true', 'half-true', 'mostly-true', 'half-true', 'half-true', 'false', 'mostly-true', 'half-true',

In [38]:
twitter=pd.DataFrame(twitter)
twitter['label']=ans




In [39]:
probability=probability.reshape(14057,1)
twitter['probability']=probability

In [40]:
twitter

Unnamed: 0              user_id            status_id  created_at  \
0           11754            495666073  1122749472180596736  1556519308   
1            1307           1956754434  1122886338930511873  1556551940   
2           13908             56569304  1122678243365203972  1556502326   
3            1818            115126046  1122921162143494144  1556560242   
4            5779   793949726483693569  1122729591590637573  1556514568   
5           13576             17823286  1122687880596475904  1556504623   
6            1172   733388252355297281  1122925194442461186  1556561203   
7           10828           3170242412  1122813040896790530  1556534464   
8            1625   856181385060536320  1122922617176973312  1556560589   
9            4715            532462766  1122896858551148551  1556554448   
10           4265           1006501890  1122900606761484288  1556555341   
11           3621  1009528938060832771  1122693499789377536  1556505963   
12            460  1096128833693061121  1122800641632624640  1556531508   
13            479           1606472113  1122679651648720896  1556502661   
14           3083            614558902  1122793661178114048  1556529843   
15           9123   804362104048230400  1122847148553330688  1556542596   
16           1631            937588736  1122922537845972994  1556560570   
17          11608           1645876892  1122758594603233280  1556521483   
18           1930             74085754  1122920293083664385  1556560035   
19           7889             14119118  1122863064657924096  1556546391   
20            662            230082885  1122927469932101632  1556561746   
21           6896  1087115363735740417  1122874884663730176  1556549209   
22           7385            374658826  1122868846078111744  1556547769   
23          13303             16472258  1122694084492009472  1556506103   
24          11681            221264989  1122754847865036800  1556520590   
25           6580   745272072998391809  1122878433694973953  1556550055   
26           1149           1179710990  1122803456895533056  1556532179   
27          12868            101043870  1122704988352831489  1556508702   
28           1008             15945641  1122880875283329024  1556550637   
29           9504           2434465868  1122842560068771840  1556541502   
...           ...                  ...                  ...         ...   
14027        7837            304691182  1122863528833093638  1556546501   
14028        5954            469737625  1122772618476605440  1556524827   
14029        1425  1021210507783487488  1122923767175491584  1556560863   
14030        9019  1061697883336921088  1122848415841341440  1556542898   
14031        8829             15880488  1122851184828669952  1556543558   
14032        6956            207682058  1122874326737408001  1556549076   
14033        4752           3383591561  1122896449828790272  1556554350   
14034        8984             97036677  1122848903878123522  1556543014   
14035        3649           2787307992  1122906151769608192  1556556663   
14036        3291            217548189  1122886198689718282  1556551906   
14037        5440   714530190945345537  1122889885126406144  1556552785   
14038        3205             36676776  1122909641250181126  1556557495   
14039        3324   834419982712729600  1122875587507499008  1556549376   
14040        5421             21990739  1122890023706091521  1556552818   
14041        2466            783185311  1122915917510402048  1556558992   
14042        1218  1091758815442231296  1122876887540228097  1556549686   
14043        8149             59219530  1122859593045106689  1556545563   
14044        4150  1032030545868451840  1122901591777054721  1556555576   
14045        2664             56040110  1122914082280095745  1556558554   
14046        8014             63770391  1122840347971870720  1556540974   
14047       12083            336847301  1122732480824528896  1556515257   
14048        8060             40

In [41]:
#twitter2.to_csv("predicted_twitter.csv", index=False,sep=',')
twitter.to_dense().to_csv("predicted_final.csv", index = False, sep=',', encoding='utf-8')

In [42]:
#READING THE CSV FILE
tw2=pd.read_csv('predicted_final.csv',delimiter=',')
tw2

Unnamed: 0              user_id            status_id  created_at  \
0           11754            495666073  1122749472180596736  1556519308   
1            1307           1956754434  1122886338930511873  1556551940   
2           13908             56569304  1122678243365203972  1556502326   
3            1818            115126046  1122921162143494144  1556560242   
4            5779   793949726483693569  1122729591590637573  1556514568   
5           13576             17823286  1122687880596475904  1556504623   
6            1172   733388252355297281  1122925194442461186  1556561203   
7           10828           3170242412  1122813040896790530  1556534464   
8            1625   856181385060536320  1122922617176973312  1556560589   
9            4715            532462766  1122896858551148551  1556554448   
10           4265           1006501890  1122900606761484288  1556555341   
11           3621  1009528938060832771  1122693499789377536  1556505963   
12            460  1096128833693061121  1122800641632624640  1556531508   
13            479           1606472113  1122679651648720896  1556502661   
14           3083            614558902  1122793661178114048  1556529843   
15           9123   804362104048230400  1122847148553330688  1556542596   
16           1631            937588736  1122922537845972994  1556560570   
17          11608           1645876892  1122758594603233280  1556521483   
18           1930             74085754  1122920293083664385  1556560035   
19           7889             14119118  1122863064657924096  1556546391   
20            662            230082885  1122927469932101632  1556561746   
21           6896  1087115363735740417  1122874884663730176  1556549209   
22           7385            374658826  1122868846078111744  1556547769   
23          13303             16472258  1122694084492009472  1556506103   
24          11681            221264989  1122754847865036800  1556520590   
25           6580   745272072998391809  1122878433694973953  1556550055   
26           1149           1179710990  1122803456895533056  1556532179   
27          12868            101043870  1122704988352831489  1556508702   
28           1008             15945641  1122880875283329024  1556550637   
29           9504           2434465868  1122842560068771840  1556541502   
...           ...                  ...                  ...         ...   
14027        7837            304691182  1122863528833093638  1556546501   
14028        5954            469737625  1122772618476605440  1556524827   
14029        1425  1021210507783487488  1122923767175491584  1556560863   
14030        9019  1061697883336921088  1122848415841341440  1556542898   
14031        8829             15880488  1122851184828669952  1556543558   
14032        6956            207682058  1122874326737408001  1556549076   
14033        4752           3383591561  1122896449828790272  1556554350   
14034        8984             97036677  1122848903878123522  1556543014   
14035        3649           2787307992  1122906151769608192  1556556663   
14036        3291            217548189  1122886198689718282  1556551906   
14037        5440   714530190945345537  1122889885126406144  1556552785   
14038        3205             36676776  1122909641250181126  1556557495   
14039        3324   834419982712729600  1122875587507499008  1556549376   
14040        5421             21990739  1122890023706091521  1556552818   
14041        2466            783185311  1122915917510402048  1556558992   
14042        1218  1091758815442231296  1122876887540228097  1556549686   
14043        8149             59219530  1122859593045106689  1556545563   
14044        4150  1032030545868451840  1122901591777054721  1556555576   
14045        2664             56040110  1122914082280095745  1556558554   
14046        8014             63770391  1122840347971870720  1556540974   
14047       12083            336847301  1122732480824528896  1556515257   
14048        8060             40